apiVersion: 1

datasources:
  - name: catalog-pg
    type: postgres
    uid: catalog-pg
    url: catalog-db:5432
    user: catalog
    secureJsonData:
      password: demo_pg_password_32chars_here_!
    jsonData:
      database: catalog
      sslmode: disable
      postgresVersion: 1600
